### ISSUE TITLE
Update debug to <3.1.0 to remove ReDOS vuln

### ISSUE THREAD

**Issue by cainwatson** [3rd-Eden/setHeader#2]
https://snyk.io/vuln/npm:debug:20170905|
https://github.com/visionmedia/debug/issues/501

**Comment by rexxars** [comment]
This is causing a cascading chain of "unsecure"-badges on anything that depends on it, for instance the  `access-control` module. +1

**Comment by 3rd-Eden** [comment]
I wouldn't really call it a vulnerability, because it's something that you manually set in your CLI, so you, as a developer are in full control of it. Having that said, i'll update it.

**Comment by 3rd-Eden** [comment]
LOL, JK.

That was easier said than done, seems like new Node has changed the way they are handling headers using a `Symbol` as key instead of string. Which is locked behind an internal constant library. Need to rewrite library first :/

**Comment by dresende** [comment]
`Object.getOwnPropertySymbols(res)` returns only one `Symbol`, which is the one used. The structure also seems to have changed, not sure. The symbols stored could increase and you wouldn't know where the headers are..

**Comment by dresende** [comment]
Look at #3
